backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: "guides"
    label: "Privacy Guides"
    folder: "content/guides"
    create: true
    slug: "{{category}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Last Modified", name: "lastmod", widget: "datetime", default: ""}
      - {label: "Categories", name: "categories", widget: "select", options: ["browsers", "messaging", "vpns", "email", "passwords", "dns", "operating-systems"], multiple: true}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Skill Level", name: "skill_levels", widget: "select", options: ["beginner", "intermediate", "advanced"], multiple: true}
      - {label: "Threat Models", name: "threat_models", widget: "select", options: ["general-privacy", "enhanced-privacy", "high-security", "activist"], multiple: true}
      - {label: "Author", name: "author", widget: "string", default: "403 Privacy Team"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Table of Contents", name: "toc", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "blog"
    label: "Blog Posts" 
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Author", name: "author", widget: "string", default: "403 Privacy Team"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "legislation"
    label: "Legislation Updates"
    folder: "content/legislation"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Bill Number", name: "bill_number", widget: "string", required: false}
      - {label: "Status", name: "status", widget: "select", options: ["introduced", "committee", "passed", "signed", "rejected"]}
      - {label: "Priority", name: "priority", widget: "select", options: ["low", "medium", "high", "urgent"]}
      - {label: "Action Required", name: "action_required", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "support-orgs"
    label: "Support Organizations"
    folder: "content/support-orgs"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Website", name: "website", widget: "string"}
      - {label: "Donation Link", name: "donation_link", widget: "string", required: false}
      - {label: "Category", name: "category", widget: "select", options: ["privacy-advocacy", "digital-rights", "security-research", "education"]}
      - {label: "Verified", name: "verified", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Homepage"
        name: "homepage"
        file: "content/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Featured Guides", name: "featured_guides", widget: "list"}
          - {label: "Recent Legislation", name: "recent_legislation", widget: "list"}
          - {label: "Body", name: "body", widget: "markdown"}
